[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Покрытие
addopts = --cov=. --cov-report=term-missing --cov-report=html --cov-exclude=tests/* --cov-exclude=venv/* --cov-exclude=.venv/*

# Логирование
log_cli = false

# Маркеры
markers =
    slow: медленные тесты
    integration: интеграционные тесты
